export const ReportData = {
  reportName: "Total Miles Driven",
  tableData: [
    {
      LicensePlate: "FE220KM",
      Make: "Tesla",
      VIN: "VIN 102",
      Model: "semi Delivery Event. 2022",
      Type: "Truck",
      Date: "2024/03/02",
      MilesDriven: "150",
    },
    {
      LicensePlate: "FE213KM",
      Make: "BYD Auto",
      VIN: "VIN 101",
      Model: "class 6F cab & chasis 2022",
      Type: "Truck",
      Date: "2024/03/01",
      MilesDriven: "250",
    },
    {
      LicensePlate: "NY220KM",
      Make: "Nikola",
      VIN: "VIN 104",
      Model: "TRE BEV. 2022",
      Type: "Truck",
      Date: "2024/03/03",
      MilesDriven: "220",
    },
    {
      LicensePlate: "FE218KM",
      Make: "Ree",
      VIN: "VIN 103",
      Model: "P7 chasis cab 2023",
      Type: "Van",
      Date: "2024/03/02",
      MilesDriven: "200",
    },
    {
      LicensePlate: "FE210KM",
      Make: "BYD Motors",
      VIN: "VIN 106",
      Model: "K7M 30 Transit Bus 2021",
      Type: "Bus",
      Date: "2024/03/05",
      MilesDriven: "150",
    },
    {
      LicensePlate: "FE210KM",
      Make: "GM Envolve",
      VIN: "VIN 105",
      Model: "Brightdrop zero 600. 2022",
      Type: "Van",
      Date: "2024/03/04",
      MilesDriven: "150",
    },
    {
      LicensePlate: "FE210KM",
      Make: "BYD Motors",
      VIN: "VIN 106",
      Model: "K7M 30 Transit Bus 2021",
      Type: "Bus",
      Date: "2024/03/05",
      MilesDriven: "150",
    },
    {
      LicensePlate: "NY220KM",
      Make: "Nikola",
      VIN: "VIN 108",
      Model: "TRE BEV. 2022",
      Type: "Truck",
      Date: "2024/03/03",
      MilesDriven: "220",
    },
    {
      LicensePlate: "FE220KM",
      Make: "Tesla",
      VIN: "VIN 107",
      Model: "semi Delivery Event. 2022",
      Type: "Truck",
      Date: "2024/03/02",
      MilesDriven: "150",
    },
    {
      LicensePlate: "FE213KM",
      Make: "BYD Auto",
      VIN: "VIN 110",
      Model: "class 6F cab & chasis 2022",
      Type: "Truck",
      Date: "2024/03/01",
      MilesDriven: "250",
    },
    {
      LicensePlate: "FY210KM",
      Make: "BYD Motors",
      VIN: "VIN 109",
      Model: "K7M 30 Transit Bus 2021",
      Type: "Truck",
      Date: "2024/03/05",
      MilesDriven: "150",
    },
  ],
};

export const formatDate = (date: Date): string => {
  const year = date.getFullYear();
  const month = ("0" + (date.getMonth() + 1)).slice(-2);
  const day = ("0" + date.getDate()).slice(-2);
  return `${year}/${month}/${day}`;
};
